### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [ktanaka117/ScrollingFollowView#4]
<img width="374" alt="screen shot 2016-09-26 at 12 12 19 am" src="https://cloud.githubusercontent.com/assets/6511079/18825552/e7ecdc56-837d-11e6-82b7-ea8663775863.png">

**Comment by ktanaka117** [comment]
Thanks for your pointing out.
I fixed it.🍣

![2016-09-27 1 56 00](https://cloud.githubusercontent.com/assets/4278711/18843876/c70cfce0-8455-11e6-9cee-86a733daa0e2.png)
